### PR TITLE
Added Chinese language support.

### PR DESCRIPTION
**Pull request by hoganliu2016**
## This PR contains:
Chinese language files and configuration

## Describe the problem you have without this PR

No problem without this PR.

### CODE REVIEW

**Comment by mbndr** [comment]
Great job :) Should solve #54

**Comment by hoganliu2016** [comment]
Thank you @mbndr! I am also thinking about adding language support for template names.

**Comment by pubkey** [comment]
Looks good. Thx @hoganliu2016 
I reviewed this with google-translate :)

**Comment by hoganliu2016** [comment]
Thank you @pubkey! :)

**Pull request merged**
