### PR TITLE
New Templates with Projects Section (Issue #4)

### PR DESCRIPTION
**Pull request by sajattack**
I did my best to add a portfolio section to all the resume templates. Some of the css is a little off but I hope it can be worked on and merged.

### CODE REVIEW

**Comment by salomonelli** [comment]
Hello @sajattack 

the PR breaks the layout of the templates, see screenshot. 

image

Please do also not commit any unchanged files like person.jpg.

**Comment by sajattack** [comment]
Can you be more specific about what is broken?

**Comment by pubkey** [comment]
@sajattack  the complete layout is broken. Its now a 3-column grid and the icons overlap the borders of the shaddow-boxes.

**Comment by sajattack** [comment]
@pubkey The 3 column-grid was intentional. I'll see what I can do about the icons.

**Comment by salomonelli** [comment]
@sajattack Please also do not adjust the existing templates, just add your changes as new ones. Then people can choose between different templates.

**Comment by sajattack** [comment]
@salomonelli I don't really have the frontend expertise to design a whole template myself.

**Comment by salomonelli** [comment]
I meant by creating a new template, you just copy your content of e.g. left-right.vue into a new file called left-right-projects.vue. Then just follow the [instructions](https://github.com/salomonelli/best-resume-ever/blob/master/DEVELOPER.md#creating-new-templates) on how to add left-right-projects.

Like this we can have two examples of a cv with projects and without. Also people can decide which one they rather like.

**Comment by sajattack** [comment]
Not sure why the pdfs are conflicting

**Comment by salomonelli** [comment]
In /src/pages/home.vue insert the added templates like this: 

```
<div class="preview">
      <router-link v-bind:to="'/resume/left-right-project'">
        <div class="preview-wrapper">
          <img src="../assets/preview/resume-left-right.png" />
          <span>left-right-project</span>
        </div>
      </router-link>
    </div>
```

Could you please try to decrease the font-sizes?

**Comment by mbndr** [comment]
Is it possible to add the template in the menu dynamically instead of writing a full html block for each template? Maybe it's also possible to create a `templates.js` file or somewhere else a list of all templates.

**Comment by salomonelli** [comment]
@mbndr PR is welcome

**Comment by sajattack** [comment]
"Could you please try to decrease the font-sizes?" I didn't increase any font sizes. Why? @salomonelli

**Comment by sajattack** [comment]
No comments on this for a while. Can you explain what you would like to see to have this merged @salomonelli ?

**Comment by salomonelli** [comment]
@sajattack Sorry, I am just like super busy :) I checked it once more, the only one that does not seem to fit is the side-bar-projects-template. Maybe you could decrease the font-size just for that one? The education part is cut off. Everything else works fine!

**Comment by sajattack** [comment]
@salomonelli How do I generate the assets for the previews on the home page?

**Comment by salomonelli** [comment]
I am going to write a script that exports the pdfs also as pngs. At the moment you will need to do this manually.

**Comment by sajattack** [comment]
@salomonelli Ok should be ready to merge now.

**Comment by danse** [comment]
this is the oldest open pull request. Is anyone interested in updating the code for merge?

**Comment by salomonelli** [comment]
Updates have been merged into the project.

**Pull request closed without merging**
